[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/topline"
  to   = "/topline.html"
  status = 200
  
[[redirects]]
  from = "/underperformers"
  to   = "/underperformers.html"
  status = 200
